# Generated by Django 5.2.1 on 2025-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tempberat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashprice',
            name='nama',
            field=models.CharField(default='', max_length=100),
        ),
    ]
