# Generated by Django 5.2.1 on 2025-05-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trashprice_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashprice',
            name='nama',
        ),
    ]
