# Generated by Django 5.2.1 on 2025-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_trashprice_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashprice',
            name='sub_kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
